# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [1]:
!pip3 install numpy

Collecting numpy
  Using cached https://files.pythonhosted.org/packages/07/08/a549ba8b061005bb629b76adc000f3caaaf881028b963c2e18f811c6edc1/numpy-1.18.2-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.18.2

In [2]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [3]:
list1= [i for i in range (1,51)]

print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [4]:
list2=[i for i in range (2,201,2)]

print(list2)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]

### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [5]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

print(a.tolist())

[[0.84062117, 0.48006452, 0.7876326, 0.77109654], [0.44409793, 0.09014516, 0.81835917, 0.87645456], [0.7066597, 0.09610873, 0.41247947, 0.57433389], [0.29960807, 0.42315023, 0.34452557, 0.4751035], [0.17003563, 0.46843998, 0.92796258, 0.69814654], [0.41290051, 0.19561071, 0.16284783, 0.97016248], [0.71725408, 0.87702738, 0.31244595, 0.76615487], [0.20754036, 0.57871812, 0.07214068, 0.40356048], [0.12149553, 0.53222417, 0.9976855, 0.12536346], [0.80930099, 0.50962849, 0.94555126, 0.33364763]]

### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [6]:
list4=[]
for i in a:
    for x in i:
        if x >= .5:
            list4.append(x)
print(list4)

[0.84062117, 0.7876326, 0.77109654, 0.81835917, 0.87645456, 0.7066597, 0.57433389, 0.92796258, 0.69814654, 0.97016248, 0.71725408, 0.87702738, 0.76615487, 0.57871812, 0.53222417, 0.9976855, 0.80930099, 0.50962849, 0.94555126]

### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [7]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [8]:
print(b.tolist())

[[[0.55867166, 0.06210792, 0.08147297], [0.82579068, 0.91512478, 0.06833034]], [[0.05440634, 0.65857693, 0.30296619], [0.06769833, 0.96031863, 0.51293743]], [[0.09143215, 0.71893382, 0.45850679], [0.58256464, 0.59005654, 0.56266457]], [[0.71600294, 0.87392666, 0.11434044], [0.8694668, 0.65669313, 0.10708681]], [[0.07529684, 0.46470767, 0.47984544], [0.65368638, 0.14901286, 0.23760688]]]

### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [9]:
list5=[]
for i in b:
    for x in i:
        if x[2]<=.5:
            list5.append(x[2])
print(list5)

[0.08147297, 0.06833034, 0.30296619, 0.45850679, 0.11434044, 0.10708681, 0.47984544, 0.23760688]

### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [10]:
list_csv= [e for e in os.listdir('../data') if e.endswith('.csv')]
print(list_csv)

['sample_file_3.csv', 'sample_file_1.csv', 'sample_file_0.csv', 'sample_file_7.csv', 'sample_file_8.csv', 'sample_file_4.csv', 'sample_file_5.csv', 'sample_file_9.csv', 'sample_file_2.csv', 'sample_file_6.csv']

### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [11]:
data_sets = [pd.read_csv(os.path.join('../data', e)) for e in list_csv]
data = pd.concat(data_sets, axis=0)
data.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.376101,0.896590,0.500995,0.381416,0.447730,0.048472,0.094235,0.986890,0.582352,0.037230,0.130306,0.766153,0.153783,0.199140,0.330318,0.969657,0.110998,0.033474,0.117277,0.213938
1,0.498192,0.565500,0.152394,0.284232,0.557042,0.417095,0.663465,0.158188,0.039182,0.543442,0.521210,0.993481,0.580359,0.765757,0.931264,0.336841,0.271230,0.509798,0.877048,0.310951
2,0.635284,0.247512,0.179986,0.468231,0.911799,0.764209,0.941413,0.808370,0.578024,0.181267,0.064788,0.924226,0.070744,0.704575,0.948127,0.971452,0.360861,0.074394,0.386949,0.396453
3,0.647497,0.072412,0.681403,0.977189,0.690953,0.829347,0.236915,0.406938,0.898234,0.513575,0.532473,0.790312,0.082292,0.850821,0.088025,0.289218,0.822775,0.515933,0.962827,0.026952
4,0.170792,0.586900,0.029834,0.921923,0.090727,0.592746,0.972429,0.774760,0.293800,0.956949,0.811740,0.525562,0.454788,0.848812,0.095214,0.415311,0.026496,0.513342,0.830389,0.931145
0,0.276827,0.260054,0.942397,0.113187,0.781355,0.475740,0.152061,0.250324,0.147078,0.162984,0.977025,0.509619,0.593212,0.911839,0.257645,0.386457,0.696932,0.069162,0.952291,0.286542
1,0.995885,0.158381,0.244274,0.962163,0.651900,0.930665,0.577190,0.087914,0.960261,0.580840,0.194616,0.661459,0.674085,0.049326,0.785803,0.315645,0.495355,0.232135,0.549324,0.572232
2,0.641917,0.821055,0.392437,0.782617,0.510762,0.428320,0.017324,0.680720,0.340412,0.462513,0.785776,0.251949,0.032847,0.995700,0.816563,0.735692,0.435998,0.430411,0.531757,0.489528
3,0.806532,0.569258,0.148175,0.809987,0.459632,0.735762,0.730664,0.934502,0.080322,0.763502,0.398504,0.027637,0.409665,0.942846,0.133256,0.157158,0.929446,0.402791,0.685976,0.246594
4,0.311185,0.501165,0.365979,0.782807,0.776795,0.797199,0.791946,0.847157,0.771811,0.233944,0.522344,0.053030,0.208551,0.824354,0.588567,0.604341,0.232964,0.229109,0.022881,0.479022

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [15]:
select_col= [c for c in data._get_numeric_data() if data[c].median()<.48]
select_col

['2', '9', '12', '14', '17']

### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [17]:
data2 = [c-0.1 for c in data["19"]]
data ["20"]=data2
data.index=range(len(data))
display(data.head(10))

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.376101,0.896590,0.500995,0.381416,0.447730,0.048472,0.094235,0.986890,0.582352,0.037230,...,0.766153,0.153783,0.199140,0.330318,0.969657,0.110998,0.033474,0.117277,0.213938,0.113938
1,0.498192,0.565500,0.152394,0.284232,0.557042,0.417095,0.663465,0.158188,0.039182,0.543442,...,0.993481,0.580359,0.765757,0.931264,0.336841,0.271230,0.509798,0.877048,0.310951,0.210951
2,0.635284,0.247512,0.179986,0.468231,0.911799,0.764209,0.941413,0.808370,0.578024,0.181267,...,0.924226,0.070744,0.704575,0.948127,0.971452,0.360861,0.074394,0.386949,0.396453,0.296453
3,0.647497,0.072412,0.681403,0.977189,0.690953,0.829347,0.236915,0.406938,0.898234,0.513575,...,0.790312,0.082292,0.850821,0.088025,0.289218,0.822775,0.515933,0.962827,0.026952,-0.073048
4,0.170792,0.586900,0.029834,0.921923,0.090727,0.592746,0.972429,0.774760,0.293800,0.956949,...,0.525562,0.454788,0.848812,0.095214,0.415311,0.026496,0.513342,0.830389,0.931145,0.831145
5,0.276827,0.260054,0.942397,0.113187,0.781355,0.475740,0.152061,0.250324,0.147078,0.162984,...,0.509619,0.593212,0.911839,0.257645,0.386457,0.696932,0.069162,0.952291,0.286542,0.186542
6,0.995885,0.158381,0.244274,0.962163,0.651900,0.930665,0.577190,0.087914,0.960261,0.580840,...,0.661459,0.674085,0.049326,0.785803,0.315645,0.495355,0.232135,0.549324,0.572232,0.472232
7,0.641917,0.821055,0.392437,0.782617,0.510762,0.428320,0.017324,0.680720,0.340412,0.462513,...,0.251949,0.032847,0.995700,0.816563,0.735692,0.435998,0.430411,0.531757,0.489528,0.389528
8,0.806532,0.569258,0.148175,0.809987,0.459632,0.735762,0.730664,0.934502,0.080322,0.763502,...,0.027637,0.409665,0.942846,0.133256,0.157158,0.929446,0.402791,0.685976,0.246594,0.146594
9,0.311185,0.501165,0.365979,0.782807,0.776795,0.797199,0.791946,0.847157,0.771811,0.233944,...,0.053030,0.208551,0.824354,0.588567,0.604341,0.232964,0.229109,0.022881,0.479022,0.379022

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [19]:
lista5=[data [c][r] for c in data for r in range(len(data)) if data [c][r]>=.7 and  data [c][r]<=.75]
lista5

[0.7347510852128797,
 0.7132714209987683,
 0.7280006345208285,
 0.7025657075988269,
 0.736029494090402,
 0.7472962776291713,
 0.7258310816144985,
 0.7343092314001137,
 0.7358941798147411,
 0.7365416322783028,
 0.7088042362916818,
 0.7329024831531535,
 0.7023481768180954,
 0.7133695725698419,
 0.7476323136755818,
 0.7008930873050235,
 0.7357618655811269,
 0.7032248108904495,
 0.7268545088531969,
 0.7150799992177622,
 0.7173964318670598,
 0.7013619954419494,
 0.7306642125209889,
 0.7124169515124726,
 0.71223975981198,
 0.7383982036983279,
 0.7298115760258881,
 0.7051334608870933,
 0.7321333453970806,
 0.7178166705957928,
 0.7374449181749492,
 0.7159290265157912,
 0.7294980584878026,
 0.7215147068185102,
 0.7045750112959754,
 0.7111584953876777,
 0.7209375615129192,
 0.7133690799930356,
 0.7303553716733908,
 0.7396561066717461,
 0.7356923324968598,
 0.7390312927111312,
 0.7078738356977186,
 0.7321533684342264,
 0.7490680818183477,
 0.7085098152301276,
 0.7130781095091867,
 0.7196096371031628,
 0.7264121114538001,
 0.7244863338885654,
 0.7393833032570581,
 0.7376946446827494,
 0.7274869207330491,
 0.7033930409580709]